name: Tests

on: [push, pull_request]

jobs:

  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: xdebug

    - uses: actions/checkout@v4

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache/files
        key: dependencies-composer-${{ hashFiles('**/composer.lock') }}


    - name: Install Composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Copy .env.example to .env
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"

        # Generate VAPID keys using web-push
        VAPID_KEYS=$(php vendor/bin/web-push generate-vapid-keys)
        PUBLIC_KEY=$(echo "$VAPID_KEYS" | grep 'Public key:' | cut -d ' ' -f 3-)
        PRIVATE_KEY=$(echo "$VAPID_KEYS" | grep 'Private key:' | cut -d ' ' -f 3-)

        echo "VAPID_PUBLIC_KEY=$PUBLIC_KEY" >> .env
        echo "VAPID_PRIVATE_KEY=$PRIVATE_KEY" >> .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Execute tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
